---
# Run all tests
stages:
  - lint
  - deployment test

# Check OS, ansible, molecule version
before_script:
  - ansible --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"
  ANSIBLE_INVENTORY: "/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible/inventory/epc.py"
  ANSIBLE_LIBRARY: "/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible"
  ANSIBLE_INVENTORY_PLUGINS: "/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible/inventory/epc.py"

# Tests for Docker driver for Platformservices 11.3.0
Docker endeca-platformservices 11.3.0:
  stage: deployment test
  script:
    - molecule test -s docker-11.3.0
  tags:
    - docker
