---
# Run all tests
stages:
  - lint
  - deployment test

# Check OS, ansible, molecule version
before_script:
  - ansible --version
  - molecule --version

variables:
  GET_SOURCES_ATTEMPTS: "5"
  ANSIBLE_INVENTORY: "/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible/inventory/epc.py"
  ANSIBLE_LIBRARY: "/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible"
  ANSIBLE_INVENTORY_PLUGINS: "/home/gitlab-runner/.local/lib/python2.7/site-packages/epam_ansible/inventory/epc.py"

# Tests for Centos 6 EPC driver for Platformservices 11.3.0
EPC Centos 6 endeca-platformservices 11.3.0:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-centos6
  tags:
    - delegated

# Tests for Centos 7 EPC driver for Platformservices 11.3.0
EPC Centos 7 endeca-platformservices 11.3.0:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-centos7
  tags:
    - delegated

# Tests for Centos 6 AWS driver for Platformservices 11.3.0
AWS Centos 6 endeca-platformservices 11.3.0:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - molecule test -s cloud-aws-centos6
  tags:
    - delegated

# Tests for Centos 7 AWS driver for Platformservices 11.3.0
AWS Centos 7 endeca-platformservices 11.3.0:
  variables:
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - molecule test -s cloud-aws-centos7
  tags:
    - delegated

# Tests for Centos 7 Docker driver for Platformservices 11.3.0
Centos 7 Docker endeca-platformservices 11.3.0:
  stage: deployment test
  script:
    - molecule test -s docker-11.3.0-centos7
  tags:
    - docker

# Tests for Centos 6 Docker driver for Platformservices 11.3.0
Centos 6 Docker endeca-platformservices 11.3.0:
  stage: deployment test
  script:
    - molecule test -s docker-11.3.0-centos6
  tags:
    - docker

# Tests for Centos 7 Docker driver for Platformservices 11.2.0
Centos 7 Docker endeca-platformservices 11.2.0:
  stage: deployment test
  script:
    - molecule test -s docker-11.2.0-centos7
  tags:
    - docker

# Tests for Centos 6 Docker driver for Platformservices 11.2.0
Centos 6 Docker endeca-platformservices 11.2.0:
  stage: deployment test
  script:
    - molecule test -s docker-11.2.0-centos6
  tags:
    - docker

# Tests for Centos 6 Docker driver for Platformservices 11.1.0
Centos 6 Docker endeca-platformservices 11.1.0:
  stage: deployment test
  script:
    - molecule test -s docker-11.1.0-centos6
  tags:
    - docker

# Tests for Centos 6 Docker driver for Platformservices 6.1.4
Centos 6 Docker endeca-platformservices 6.1.4:
  stage: deployment test
  script:
    - molecule test -s docker-6.1.4-centos6
  tags:
    - docker

# Tests for Centos 6 Docker driver for Platformservices 6.1.3
Centos 6 Docker endeca-platformservices 6.1.3:
  stage: deployment test
  script:
    - molecule test -s docker-6.1.3-centos6
  tags:
    - docker
