---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - ansible --version
  - molecule --version
#  - ansible-config dump --only-changed

variables:
  GET_SOURCES_ATTEMPTS: "5"

Ansible lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - delegated

# Tests for Centos 7 EPC driver for Platformservices 11.3.0
.EPC Centos 7 endeca-platformservices 11.3.0:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-centos7
  tags:
    - delegated

# Tests for Centos 6 AWS driver for Platformservices 11.3.0
AWS Centos 6 endeca-platformservices 11.3.0:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-centos6
  tags:
    - aws

# Tests for Centos 7 AWS driver for Platformservices 11.3.0
AWS Centos 7 endeca-platformservices 11.3.0:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-centos7
  tags:
    - aws

# Tests for Centos 7 Docker driver for Platformservices 11.3.0
Centos 7 Docker endeca-platformservices 11.3.0:
  stage: deployment test
  script:
    - molecule test -s docker-11.3.0-centos7
  tags:
    - aws

# Tests for Centos 6 Docker driver for Platformservices 11.3.0
Centos 6 Docker endeca-platformservices 11.3.0:
  stage: deployment test
  script:
    - molecule test -s docker-11.3.0-centos6
  tags:
    - aws

# Tests for Centos 7 Docker driver for Platformservices 11.2.0
Centos 7 Docker endeca-platformservices 11.2.0:
  stage: deployment test
  script:
    - molecule test -s docker-11.2.0-centos7
  tags:
    - aws

# Tests for Centos 6 Docker driver for Platformservices 11.2.0
Centos 6 Docker endeca-platformservices 11.2.0:
  stage: deployment test
  script:
    - molecule test -s docker-11.2.0-centos6
  tags:
    - aws

# Tests for Centos 6 Docker driver for Platformservices 11.1.0
Centos 6 Docker endeca-platformservices 11.1.0:
  stage: deployment test
  script:
    - molecule test -s docker-11.1.0-centos6
  tags:
    - aws

# Tests for Centos 6 Docker driver for Platformservices 6.1.4
Centos 6 Docker endeca-platformservices 6.1.4:
  stage: deployment test
  script:
    - molecule test -s docker-6.1.4-centos6
  tags:
    - aws

# Tests for Centos 6 Docker driver for Platformservices 6.1.3
Centos 6 Docker endeca-platformservices 6.1.3:
  stage: deployment test
  script:
    - molecule test -s docker-6.1.3-centos6
  tags:
    - aws
