---
- name: "Read content of {{ version_txt }}"
  slurp:
    src: "{{ version_txt }}"
  register: remote_conf

- name: "Set version_properties"
  set_fact:
    version_properties: "{{ remote_conf['content'] | b64decode }}"

- name: "Set regex string"
  set_fact:
    regex_value: "VERSION: {{ ps_version }}"

- name: "Check if patch installed"
  set_fact:
    patch_installed: True
  when: "version_properties | regex_search(regex_value)"
