---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-6.1.3-centos6
    image: centos:6
    privileged: True
    groups:
      - rhel_family
provisioner:
  name: ansible
  log: True
  lint:
    name: ansible-lint
scenario:
  name: docker-6.1.3-centos6
verifier:
  name: testinfra
  options:
    verbose: True
  directory: ../resources/tests/
  lint:
    name: flake8
