---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.endeca_mdex
      transport: "web"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/commerce/endeca10.2/V40319-01.zip"
    - role: ansible-role-endeca-platformservices
      transport: "web"
      ps_version: "6.1.4"
      transport_web: "{{ lookup('env','STORAGE_EPC') }}/oracle-commerce-suite/commerce/endeca10.2/V40324-01.zip"
  vars:
    mdex_version: "6.4.1.2"
